---
title: "Untitled"
output: html_document
date: "2023-04-14"
---



### This script is used for checking distances between WOSIS data and GFBI data. 


Load the silt dataset extracted from QGIS. 
```{R}


silt <- read.csv('~/Desktop/silt_demo.csv')


nrow(silt)

head(silt)


```

Load the packages that will be used. 

```{R}
library(ggplot2)

library(dplyr)


library(zoo)

library(maps)


```

Check the global distributions of silt data. 


```{R}
worlddata <- map_data('world')

ggplot() + 
  geom_map(data = worlddata, map = worlddata, aes(x = long, y = lat, group = group, map_id = region), fill = '#bcbcbc', color = '#bcbcbc', size = 0.5)+
  geom_point(data = silt, aes(x = Y, y = X))


```

We don't need to many columns from silt dataset. We only need longitude, latitude and point-level measurements.

```{R}

silt <- silt %>%
  dplyr::select(c(Y, X, silt_value_avg))


names(silt) <- c('Longitude', 'Latitude', 'silt_value_avg')



```
Same processing applied to clay content dataset. 

```{R}

clay <- read.csv('~/Desktop/clay_demo.csv')




```


```{R}


worlddata <- map_data('world')

ggplot() + 
  geom_map(data = worlddata, map = worlddata, aes(x = long, y = lat, group = group, map_id = region), fill = '#bcbcbc', color = '#bcbcbc', size = 0.5)+
  geom_point(data = clay, aes(x = Y, y = X))


```

Load the full version of GFBi dataset. The file name is from another project using GFBi dataset, but also contain the information that needed for this leaf type project. 

```{R}
fft <- read.csv('~/Desktop/fullgfbi_standardized_20230330_66domi.csv')

head(fft)

names(fft)

```
```{R}

summary(fft$bd)

fft$rowinde <- 1:nrow(fft)

```



```{R}
library(dplyr)

library(geosphere) # where the function "distm" is from.



```

Below is a trial to illustrate how the "distm" function works. To do so, we need a subset of GFBi.

```{R}

subfft <- fft %>%
  sample_n(., 1)

subfft[,c('longitude', 'latitude')]

```

Run the "distm" function from the package "geosphere".
```{R}

ss <- distm(subfft[,c('longitude', 'latitude')], silt[,c('Longitude', 'Latitude')], fun = distHaversine)




which.min(ss)

ss[which.min(ss)]

```

Now we initialize a function that can systematically process the GFBi dataset by calculating the neariest distance to a WOSIS point and get the soil feature value (here the value is silt content). 

```{R}
# function for getting the soil feature.
locator <- function(df, soildf) {
  library(geosphere)
  
  ss <- distm(df[,c('longitude', 'latitude')], soildf[,c('Longitude', 'Latitude')], fun = distHaversine)
  
  return(silt[which.min(ss),'silt_value_avg'])
}


# Function for getting the nearest distance to WOSIS point.
minsoil <- function(df, soildf){
  ss <- distm(df[,c('longitude', 'latitude')], soildf[,c('Longitude', 'Latitude')], fun = distHaversine)
  return(min(ss))
  
}

```


We here split gfbi dataset into 4 sub-datasets to release the pressure of computer storage. Below shows the last piece. 

```{R}

fftsample <- fft[1000001:nrow(fft),]



demosoil <- fftsample %>%
  group_by(plot_id) %>% # "plot_id" is the key to locate each unique plot in GFBi. 
  do(data.frame(siltmin = minsoil(.,silt),
                siltvalue = locator(.,silt))) %>%
  ungroup()



```


```{R}

summary(demosoil$siltmin)


```

See how many points remain if we set a maximum distance threshold. 
```{R}

nrow(demosoil[demosoil$siltmin<=1000,])


```

Output

```{R}

library(readr)

write_csv(demosoil, '~/Desktop/soil_silt_match_distance_4.csv')


```


