---
title: "leafhabit_grsearch_h2o"
author: "Haozhi Ma"
date: "11/15/2019"
output: html_document
---

### This script is used to do grid search of sampled wpda subsamples. 

load the 0.01 proportion replicate 1.

```{R}
df<-read.csv('C:\\Users\\haozh\\Desktop\\LL\\subsample_grsearch\\wdpa\\wdpa_subsamp_repli1_0.01proportion.csv')
names(df)

```

deselect the covariates that we do not want

```{R}
#bandnames<-names(forest.rsr.grsearch)
bands<-subset(df, select = -c(X.2,X.1,Abs_Lat, system.index,latitude,longitude,Pixel_Lat, Pixel_Long,tree_density,.geo,X,Unnamed__0, cover, dbhpheno, spcover, spdbhcor, spdbhph, spph, spphcor, yr,pheno))
bandnames<-names(bands)
print(bandnames)
```

load the package

```{R}
library(data.table)
library(h2o)
library(raster)
library(tictoc)
library(foreach)
library(doParallel)
library(tidyverse)

```

load the data

```{R}
rawmatrix<-df

```

set the name of the dependent variable

```{R}
vartomodel<-'pheno'

```

select the bands from the regression matrix

```{R}
regressionmatrix<-rawmatrix %>%
  select(bandnames, vartomodel)
regressionmatrix$pheno<-regressionmatrix$pheno*100
```

initiate the working environment

```{R}
localH2O<-h2o.init(nthreads = 7, max_mem_size = '500g', ignore_config = TRUE)

```

import the regression matrix

```{R}
regmatrixh2o<-as.h2o(regressionmatrix, destination_frame = 'regMatrixH2O')

```


simple rf model, no grsearch

```{R}
rf.model.ll<-h2o.randomForest(
  y = vartomodel,
  training_frame = regmatrixh2o,
  ntrees = 100,
  mtries = 4,
  min_rows = 4,
  sample_rate = 0.632,
  nfolds = 10,
  fold_assignment = 'Modulo',
  keep_cross_validation_predictions = TRUE,
  seed = 0
)

h2o.varimp_plot(rf.model.ll)

h2o.r2(rf.model.ll, xval = TRUE)

```


doing plots


```{R}
fullprediction<-as.data.frame(h2o.predict(rf.model.ll,regmatrixh2o))

trainandpredicted<-as.data.frame(fullprediction)

trainandpredicted$train<-regressionmatrix[[vartomodel]]

```

define palette

```{R}
paletteForUse <- c('#d10000', '#ff6622', '#ffda21', '#33dd00', '#1133cc', '#220066', '#330044')
colors <-  colorRampPalette(paletteForUse)(256)

trainandpredicted$dens <- col2rgb(densCols(trainandpredicted$train, trainandpredicted$predict))[1,] + 1L
trainandpredicted$colors = colors[trainandpredicted$dens]

summary(lm(predict ~ train, data = trainandpredicted))

```

```{R}
ggplot(trainandpredicted, 
                      aes(x = predict, 
                          y = train)) +
  geom_point(color = trainandpredicted$colors) +
  labs(x = "Predicted",
       y = "Observed") +
  coord_cartesian(xlim = c(0,100), ylim = c(0,100)) +
  stat_smooth(se = T,
              colour = "black",
              size = 0.5,
              method = "lm") +
  geom_abline(slope = 1,
              intercept = 0,
              na.rm = FALSE, 
              show.legend = NA, 
              linetype = "dashed") +
  theme_bw()

```

we will use 5% as the proportion.

load the 0.05 proportion replicate.

```{R}
df<-read.csv('C:\\Users\\haozh\\Desktop\\LL\\subsample_grsearch\\wdpa\\wdpa_subsamp_repli6_0.05proportion.csv')
names(df)

```

```{R}
df.for.shp<-df[,c(81,82,87,88,91,94,95,96,97,98,100)]
library(rgdal)

coordinates(df.for.shp)<-~longitude+latitude
proj4string(df.for.shp)<-CRS('+init=epsg:4326')

writeOGR(df.for.shp, 'C:\\Users\\haozh\\Desktop\\LL\\subsample_grsearch\\wdpa\\wdpa_shapefiles','wdpa_repli_20','ESRI Shapefile')


```





deselect the covariates that we do not want

```{R}
#bandnames<-names(forest.rsr.grsearch)
bands<-subset(df, select = -c(X.2,X.1,Abs_Lat, system.index,latitude,longitude,Pixel_Lat, Pixel_Long,tree_density,.geo,X,Unnamed__0, cover, dbhpheno, spcover, spdbhcor, spdbhph, spph, spphcor, yr,pheno))
bandnames<-names(bands)
print(bandnames)
```

load the package

```{R}
library(data.table)
library(h2o)
library(raster)
library(tictoc)
library(foreach)
library(doParallel)
library(tidyverse)

```

load the data

```{R}
rawmatrix<-df

```

set the name of the dependent variable

```{R}
vartomodel<-'pheno'

```

select the bands from the regression matrix

```{R}
regressionmatrix<-rawmatrix %>%
  select(bandnames, vartomodel)
regressionmatrix$pheno<-regressionmatrix$pheno*100
```

initiate the working environment

```{R}
localH2O<-h2o.init(nthreads = 7, max_mem_size = '500g', ignore_config = TRUE)

```

import the regression matrix

```{R}
regmatrixh2o<-as.h2o(regressionmatrix, destination_frame = 'regMatrixH2O')

```
set grsearch hyperparameter
```{R}
rf.params<-list(ntrees = 100,
                mtries = c(2:10,20,30),
                min_rows = c(2:5))

```

set grsearch criteria

```{R}
search.criteria<-list(strategy = 'RandomDiscrete', max_models = 44, seed = 0)
```

perform rf grsearch across parameters

```{R}
rf.grid<-h2o.grid('randomForest',
                  y = vartomodel,
                  grid_id = 'rf.grid',
                  training_frame = regmatrixh2o,
                  seed = 0,
                  hyper_params = rf.params,
                  sample_rate = 0.632,
                  nfolds = 10,
                  search_criteria = search.criteria)
```

retireve grid searched model preformance sorted by R2

```{R}
rf.grid.perf<-h2o.getGrid(grid_id = 'rf.grid',
                          sort_by = 'R2',
                          decreasing = TRUE)

```

```{R}
print(rf.grid.perf@summary_table)


```

save the hyperparameters into tables

```{R}
write.csv(rf.grid.perf@summary_table, 'C:\\Users\\haozh\\Desktop\\LL\\subsample_grsearch\\wdpa\\bestmodels\\wdpa_param_repli5_pheno.csv')

```

we also need to convert csv to shapefile 






